version: "3.9"

services:
  api:
    build: .
    container_name: bondwatch_api
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - PYTHONUNBUFFERED=1

  redis:
    image: redis:7-alpine
    container_name: bondwatch_redis
    ports:
      - "6379:6379"

  worker:
    build: .
    container_name: bondwatch_worker
    command: celery -A app.celery_tasks.celery_app.celery worker --loglevel=info
    depends_on:
      - api
      - redis
    environment:
      - PYTHONUNBUFFERED=1

  flower:
    build: .
    container_name: bondwatch_flower
    command: celery -A app.celery_tasks.celery_app.celery flower --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - api
      - redis
