"""extend bonds table with MOEX fields

Revision ID: 13a88baab0d6
Revises: dd68f0683863
Create Date: 2025-09-10 20:17:15.295395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13a88baab0d6'
down_revision: Union[str, Sequence[str], None] = 'dd68f0683863'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bonds', sa.Column('secid', sa.String(), nullable=True))
    op.add_column('bonds', sa.Column('shortname', sa.String(), nullable=True))
    op.add_column('bonds', sa.Column('matdate', sa.Date(), nullable=True))
    op.add_column('bonds', sa.Column('facevalue', sa.Float(), nullable=True))
    op.add_column('bonds', sa.Column('initial_facevalue', sa.Float(), nullable=True))
    op.add_column('bonds', sa.Column('coupon_percent', sa.Float(), nullable=True))
    op.add_column('bonds', sa.Column('coupon_value', sa.Float(), nullable=True))
    op.add_column('bonds', sa.Column('coupon_date', sa.Date(), nullable=True))
    op.create_index(op.f('ix_bonds_secid'), 'bonds', ['secid'], unique=False)
    op.drop_column('bonds', 'name')
    op.drop_column('bonds', 'yield_percent')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bonds', sa.Column('yield_percent', sa.FLOAT(), nullable=False))
    op.add_column('bonds', sa.Column('name', sa.VARCHAR(), nullable=False))
    op.drop_index(op.f('ix_bonds_secid'), table_name='bonds')
    op.drop_column('bonds', 'coupon_date')
    op.drop_column('bonds', 'coupon_value')
    op.drop_column('bonds', 'coupon_percent')
    op.drop_column('bonds', 'initial_facevalue')
    op.drop_column('bonds', 'facevalue')
    op.drop_column('bonds', 'matdate')
    op.drop_column('bonds', 'shortname')
    op.drop_column('bonds', 'secid')
    # ### end Alembic commands ###
