"""init schema

Revision ID: 6f38389c1ce0
Revises: 
Create Date: 2025-09-12 21:11:41.011940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f38389c1ce0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bonds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isin', sa.String(), nullable=True),
    sa.Column('secid', sa.String(), nullable=True),
    sa.Column('shortname', sa.String(), nullable=True),
    sa.Column('matdate', sa.Date(), nullable=True),
    sa.Column('facevalue', sa.Float(), nullable=True),
    sa.Column('initial_facevalue', sa.Float(), nullable=True),
    sa.Column('coupon_percent', sa.Float(), nullable=True),
    sa.Column('coupon_value', sa.Float(), nullable=True),
    sa.Column('coupon_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bonds_id'), 'bonds', ['id'], unique=False)
    op.create_index(op.f('ix_bonds_isin'), 'bonds', ['isin'], unique=True)
    op.create_index(op.f('ix_bonds_secid'), 'bonds', ['secid'], unique=False)
    op.create_table('coupon_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bond_id', sa.Integer(), nullable=True),
    sa.Column('coupon_date', sa.Date(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('valueprc', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['bond_id'], ['bonds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coupon_schedule_id'), 'coupon_schedule', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coupon_schedule_id'), table_name='coupon_schedule')
    op.drop_table('coupon_schedule')
    op.drop_index(op.f('ix_bonds_secid'), table_name='bonds')
    op.drop_index(op.f('ix_bonds_isin'), table_name='bonds')
    op.drop_index(op.f('ix_bonds_id'), table_name='bonds')
    op.drop_table('bonds')
    # ### end Alembic commands ###
