"""add currency to coupon_schedule

Revision ID: 7a42eafdbd79
Revises: 6f38389c1ce0
Create Date: 2025-09-13 16:33:30.238364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a42eafdbd79'
down_revision: Union[str, Sequence[str], None] = '6f38389c1ce0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bonds_id'), table_name='bonds')
    op.add_column('coupon_schedule', sa.Column('currency', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coupon_schedule', 'currency')
    op.create_index(op.f('ix_bonds_id'), 'bonds', ['id'], unique=False)
    # ### end Alembic commands ###
