"""create bonds table

Revision ID: dd68f0683863
Revises: 
Create Date: 2025-09-07 13:14:15.486703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd68f0683863'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bonds',
    sa.Column('isin', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('yield_percent', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('isin')
    )
    op.create_index(op.f('ix_bonds_isin'), 'bonds', ['isin'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bonds_isin'), table_name='bonds')
    op.drop_table('bonds')
    # ### end Alembic commands ###
